spring.application.name=HealthCare
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.cache.type=${SPRING_CACHE_TYPE:simple}
spring.data.redis.url=${SPRING_DATA_REDIS_URL:}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:premium-possum-101622.upstash.io}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME:}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:${SPRING_DATA_REDIS_SSL:false}}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT:5s}
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

jwt.secret=${JWT_SECRET:MaCleSecreteSuperLongueEtSecurisee1234567890!}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true